### ISSUE TITLE
App upload to shopware account is missing correct supported versions

### ISSUE THREAD

**Issue by bilobait-lohrmann** [FriendsOfShopware/shopware-cli#191]
### PHP Version

8.2

### Shopware Version

6.5

### Actual behaviour

If an app zipfile is uploaded to the shopware account the release is missing the shopware 6.5 as supported version

### Expected behaviour

Also the shopware 6.5 versions should be selected in the release as supported versions

### Steps to Reproduce?

Upload an app to the account and check in the release if shopware 6.5 is supported

**Comment by bilobait-lohrmann** [comment]
Can you please point me out how the config should look like? I don't find any information here https://sw-cli.fos.gg/shopware-extension-yml-schema/#reference-config

**Comment by bilobait-lohrmann** [comment]
Thank you

**Comment by bilobait-lohrmann** [comment]
I tried 
shopwareVersionConstraint: "^6.4.12 || ^6.5"

but still the complete 6.4 is selected and 6.5 not

**Comment by shyim** [comment]
Fixed with https://github.com/FriendsOfShopware/shopware-cli/releases/tag/0.1.74
create a new zip

**Comment by bilobait-lohrmann** [comment]
still not working. After Upload all SW 6.4 versions are selected and none of the 6.5. If I create a new zip, inside the container there are also no version information or do I miss something?
